### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by pimduijst** [Laravel-Backpack/Demo#11]
Oke, I may sound like a noob but I am running into a next issue. I have installed everything succesfully and using Mamp Pro I've assigned a local url refering to the document root. When I navigate to that url I get an error message 'You don't have permission to acces / on this server.'

What am I doing wrong or missing?

**Comment by tabacitu** [comment]
Hi @pimduijst ,

Did you navigate to the public folder? Using MAMP you should be able to use it at:
- http://localhost/projectname/public
- http://projectname if you setup the virtual host to point to your **project/public** folder

I guess this means you don't have a lot of experience in Laravel. I strongly recommend you go through "[Laravel from Scratch](https://laracasts.com/skills/laravel)" in Laracasts. Otherwise you will find things frustrating, if you try to climb both Laravel's and Backpack's learning curves at once.

Cheers!

**Comment by pimduijst** [comment]
Hi,

true that I am still pretty new to Laravel, and I had my document root pointing to the wrong directory. Thanks for the fast response and sorry for the noobish question ;)

Cheers!
