### ISSUE TITLE
User permissions should work out of the box?

### ISSUE THREAD

**Issue by noxidsoft** [Laravel-Backpack/Demo#124]
# Bug report ?

### What I did:
Standard localhost install on Windows WAMP

### What I expected to happen:
User permissions should work out of the box?

### What happened:
Registering, and/or creating a new User, with or without current (seeded) permissions/roles/etc, any user can do anything. e.g. no restrictions observed for any user no matter their role or permission setting(s)

### What I've already tried to fix it:
I want to know if I missed something in setup from the boxed app

### Backpack, Laravel, PHP, DB version:
Backpack: 
Current as at today's date - https://github.com/Laravel-Backpack/Demo/blob/master/composer.json

Laravel:
Laravel Installer 2.2.0

PHP: 
PHP 7.2.18 (cli)

DB: 
MySQL 5.7.26

I was hoping the permissions would work out of the box so I can learn how this should be done for my own project, from your demo.

**Comment by noxidsoft** [comment]
More specifically, I guess I'm asking if Gates / Policies have been added at a basic level in the backpack code - https://laravel.com/docs/6.x/authorization#writing-gates

**Comment by tabacitu** [comment]
Hi @noxidsoft ,

Indeed, **spatie/laravel-permission** does NOT use gates and policies. Restricting access is done using their helpers and methods. Take a closer look at the https://github.com/spatie/laravel-permission package - ours is just _an interface_ to manage entries, if you're using that package.

To be honest, I don't see a reason why we should complicate things inside the Demo, and restrict access to certain parts, according to roles/permissions. Indeed, the demo _would_ be more complete and accurate, but it would have the big downside of making it more difficult to use/understand. Say we split the panels into separate Roles (superadmin, admin, editor, visitor). By default:
- the register form would make sense to create ```visitors```;
- the command line would make sense to create ```superadmins```;
- the bogus info we seed would be of different random roles;

So when testing things, which is usually done fast, you'll sometimes have access to features, sometimes no. Which would be frustrating.

Plus, a lot of people don't actually deny access using roles, but using permissions. So that example would need to be created too.

If you take both into account, **I think it would create more problems than it solves**, considering the fact that **this is just a DEMO repo - not for actual production use**. Yes, it would provide examples. But **it would bloat the codebase to provide examples on how to use a package that we don't own** (spatie/laravel-permission). So I think it's better if we keep it as it is now - just a basic implementation of the interface, and allow people to use spatie/laravel-permission as they want (using roles, permissions or both).

Let me know if you still don't agree after my arguments, and we'll reopen the issue. Like everybody else, I'm wrong at least once a day :smile:

Cheers!

PS. I do agree we could provide tips on implementation in our README.md though. It certainly wouldn't hurt 😄  Personally I prefer to have [middleware that checks for a certain permission/role](https://gist.github.com/tabacitu/acd7929cc9f60d104da1df4c39f0dad2), and use those middleware in my ```routes/backpack/custom.php``` file, or in ```config/backpack/base.php``` as a default middleware, if there's a "superadmin" role.
