### ISSUE TITLE
Request to add Dockerfile

### ISSUE THREAD

**Issue by CHOMNANP** [Laravel-Backpack/demo#191]
# Bug report

### What I did:
Adding docker file.
### What I expected to happen:
It would work.
### What happened:
It does not work.
### What I've already tried to fix it:
Trying to fix ocker file.
### Backpack, Laravel, PHP, DB version:
Master branch.

I would suggest to add docker file in the repo.

**Comment by tabacitu** [comment]
@CHOMNANP , we don't have a plan to make it easier to install the demo using docker - there are many _many_ dev env options for Laravel, docker is just one, and it's one that we the maintainers do not use or prefer. What we've provided here is a _general_ repo, that can be installed no matter what local env you choose. And the commands we've outlined here should be super easy to follow - https://github.com/Laravel-Backpack/demo#install . What I mean by this is that we don't make it easy for those using Docker to install the demo, but we don't make it difficult either.

That being said, if you or anybody else submits a dockerfile to make it easier for those that prefer that, we will consider merging it, of course.

Cheers!

**Comment by eduardoarandah** [comment]
@tabacitu the benefit for maintainability is in our favor. 

With docker you run one command and are guaranteed to get the exact same environment, so environment bugs can’t be blamed on this package. 

docker-compose up -d 

Also, environment bugs can be reproduced easily.  Let’s say, “it breaks in php8 form with nginx and mariadb 10.12, docker-compose.yml attached” 

Want me to branch with an example?

**Comment by tabacitu** [comment]
Sure, thanks! 

Currently the demo is [tested using TravisCI](https://travis-ci.com/github/Laravel-Backpack/demo) and auto-deployed on [demo.backpackforlaravel.com](https://demo.backpackforlaravel.com/admin/login). This combo makes sure that it installs well on the supported version when there's a PR/change. If `master` changes, the server automatically gets updated, and even in that case, I will receive emails with the error messages from the server. Sure, TravisCI also allows us to test _multiple_ versions, but we don't do that, we only support using PHP 7.4 for the demo, which is the PHP version on the server, and we force that PHP inside `composer.json`. 

I'm explaining how it currently works as a prelude to this heads-up: I'm not interested in changing demo.backpackforlaravel.com to use docker, I'm very happy with Laravel Forge 😄 Since there's zero benefit to changing something that works well, it's not worth the cost. 

But I _am interested_ in making it easier for people who do _use_ and _prefer_ docker on localhost, to quickly install this. If it's just one file that we can provide, and only change when we bump versions, I say let's provide it!
