### ISSUE TITLE
Cannot add a NOT NULL column with default value NULL

### ISSUE THREAD

**Issue by andreich1980** [Laravel-Backpack/Demo#20]
I've got the error after I run `php artisan migrate`
The problem was in 
```
database\migrations\2016_07_24_060017_add_slug_to_categories_table.php
database\migrations\2016_07_24_060101_add_slug_to_tags_table.php
```
in the string 
```
$table->string('slug')->unique()->after('name');
```

I added `nullable()` and it's gone. 

Does it happen only for me?

**Comment by OwenMelbz** [comment]
Showing the actually error is always helpful :P

But I guess the issue is because your database is set up as Strict, so in a way its the database erroring rather than the application itself.

It would be worth [trying to change your database type](https://www.google.co.uk/search?q=mysql+disable+strict+mode&oq=mysql+disable+strict+mode&aqs=chrome..69i57.2378j0j7&sourceid=chrome&ie=UTF-8) and testing again.

The bit that does confuse me is the fact the migrations should not be inserting any data - so why that error would trigger I do not know!

But if you can share the actual error that would be helpful please :)

**Comment by andreich1980** [comment]
I set up simple sqlite database.

```
D:\Dropbox\OpenServer\domains\backpack-demo>php artisan migrate
Migration table created successfully.


  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL (SQL: alter table "categories" add column "slug" varchar not null)



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL



  [PDOException]
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL



D:\Dropbox\OpenServer\domains\backpack-demo>php artisan migrate


  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL (SQL: alter table "tags" add column "slug" varchar not null)



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL



  [PDOException]
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL
```

**Comment by OwenMelbz** [comment]
Apparently this is a known SQLite thing -> http://stackoverflow.com/questions/3170634/how-to-solve-cannot-add-a-not-null-column-with-default-value-null-in-sqlite3

**Comment by andreich1980** [comment]
Thanks! I close the issue then.

**Comment by tanmaysathe** [comment]
Thanks andreich & Owen.

**Comment by Fatih90** [comment]
Thanks @OwenMelbz setting the strict value to false fixed it
