### ISSUE TITLE
model_function_attribute

### ISSUE THREAD

**Issue by blondie63** [Laravel-Backpack/demo#329]
Try to use model_function_attribute i'm looking in code of your demo:
app/Http/Controllers/Admin/MonsterCrudController.php
line 224

here there a addColumn but running app i don't see it
where is the problem ?

Are you sure that model_function_attribute is working fine?
Testing it on my project does'nt works.. unfortunately docs is not clear and there's no right sample code to use it :(

**Comment by tabacitu** [comment]
Hey @blondie63 ,

Just tested it - it shows and it works fine:
<img width="1280" alt="Screenshot 2021-12-09 at 16 47 58" src="https://user-images.githubusercontent.com/1032474/145418348-3ac3fac4-522e-479c-afb4-d24a993cf873.png">

So this is not a bug in Backpack. Must be the way you're using it. 

You'll find the definition in the docs and and example in the demo, should help you out. Basically it's the same as `model_function` but you it goes one level deeper if the result is an object.

Cheers!

**Comment by blondie63** [comment]
this column get attribute from getCategory() function but where can i save it to test locally ?
Anyway, Really i don’t understand if i can use model_function_attribute to read a json field saved with crud-fields#address_google-1 :(

**Comment by tabacitu** [comment]
> this column get attribute from getCategory() function but where can i save it to test locally ?

This is an example that calls a `getCategory()` function on the Monster model. You don't save it... you create your own function in the model, whatever name you want, then point the column type to that function.

There is no existing function in Laravel models that get an attribute, unless you've defined a Laravel accessor. So no, you won't be able to use that directly to access a particular part of the address JSON. But you can 
- create a function on your model that returns that address, then use that function in the column;
- OR
- use the `json` column type;

Hope it helps. Please reserve Github only for bugs, otherwise it distracts us from fixing bugs and creating new features.

Cheers!
