### ISSUE TITLE
Installing Demo require Backpack pro

### ISSUE THREAD

**Issue by hellodit** [Laravel-Backpack/demo#383]
I just want to ask, why does installing a backpack demo require a backpack pro account?

Can i use this demo using backpack free account? 

![image](https://user-images.githubusercontent.com/32544683/163720640-91298b0e-f585-4471-b28e-51a4f4610135.png)

**Comment by tabacitu** [comment]
Hey @hellodit ,

Indeed - in order to show off ALL backpack features, including the PRO ones, our demo uses `backpack/pro` too. That's why it requires a user & token, to access the closed-source package..

We're considering creating a separate demo without `backpack/pro`, but right now you can do that using:
```php
# create a new laravel project
laravel new someprojectname
cd someprojectname

# TODO: create a new db and use it in your .env file

# install backpack
composer require backpack/crud
php artisan backpack:install
```

**Comment by hellodit** [comment]
Thanks @tabacitu for your answer,
it will be nice if users have the option to install demos with or without pro features.
