### ISSUE TITLE
Feature Request: Content list with bulk actions.

### ISSUE THREAD

**Issue by chriscalip** [Laravel-Backpack/Demo#52]
# Feature Request

Example is demo for /admin/article. Lets have bulk action publish/unpublish.

Check out https://github.com/yajra/laravel-datatables-editor/issues/1 for an implementation example.

**Comment by tabacitu** [comment]
Hi @chriscalip . 

Noted, thank you. 

But I don't think a demo for this will be coming very soon, to be honest. Yes, there are ways to achieve this right now - definitely. I would have pointed you to [this datatables plugin](https://datatables.net/extensions/select/examples/initialisation/checkbox.html). But **we have a plan to provide bulk actions _as a Backpack\CRUD functionality_**. To make it _way easier_ to implement bulk actions, with a clear API and all that. And I think _that_ is a way better moment to provide a demo. Otherwise we'd just be promoting a "workaround" or "custom solution".

Hope you understand. 

If you do need bulk actions right now, and create them in one of your projects, I'd love it if you could create a blog post or tutorial about it. I'm sure a lot of Backpack developers would love you for it, and I'd be happy to promote it within the Backpack newsletter and our other marketing channels. This could be on [the Backpack blog](https://backpackforlaravel.com/articles), your Medium, your blog, whatever you want. 

Thanks, cheers!
