### ISSUE TITLE
Menu items not showing

### ISSUE THREAD

**Issue by lguima** [Laravel-Backpack/Demo#54]
# Bug report

### What I did:
I created new menu items with external links.

![screenshot from 2018-01-10 09-37-24](https://user-images.githubusercontent.com/1562097/34770956-fa968cf0-f5e9-11e7-8658-afaca5aa8809.png)

### What I expected to happen:
I expect to see them somewhere on sidebar menu.

### What happened:
I didn't see them anywhere.

![screenshot from 2018-01-10 09-38-57](https://user-images.githubusercontent.com/1562097/34770995-1f2254a0-f5ea-11e7-8583-1d9c1bb09ed1.png)

### What I've already tried to fix it:
I read the [MenuCRUD documentation](https://laravel-backpack.readme.io/docs/menu-crud) and realized that in demo project, there's no model nether controller relative to that project.

Should I put them on my project? Shouldn't that files already be on the demo project?

### Backpack, Laravel, PHP, DB version:
0.8.2, 5.5.22, 7.1.12, 5.7.20

**Comment by tabacitu** [comment]
Hi @lguima ,

MenuCRUD is not usually used to add stuff in the Admin Menu (back-end). It's usually used for the front-end menu, that users can see. So no, adding a menu item in MenuCRUD will not add a menu item in the sidebar you see, though you can customize ```sidebar.blade.php``` to do that, if you'd like. 

We'll change the description too, so that it's more clear.

Thanks for the detailed bug report. 
Cheers!
