### ISSUE TITLE
Demo erros pos installation

### ISSUE THREAD

**Issue by valle6** [Laravel-Backpack/Demo#7]
Sorry by ignorance , I'm learning Laravel . I've installed the backpack-demo and I do not know how see articles in frontend. I've tryed rest url format and nothing. Trying to view pages by slug (button "open" in backend page list) produces error 404. Menu Advanced > Settings > " Contact form CC field" and " Contact form email address" produce error "ErrorException in Fields.php line28 : Undefined index : name".
I haven't configured virtual host and mod-rewrite in Apache to backpack-demo project, but backend seems ok.
Thanks .

**Comment by tabacitu** [comment]
Hi, @valle6 ,

I'm not sure if Backpack is the right package to be learning Laravel on. It's using quite a few Laravel tricks and that might make your learning curve even bigger. Heavily recommend [Laracasts](https://laracasts.com/) and a few custom projects first.

That being said:
- it's ok, you don't really need virtual host unless you hate the long urls;
- the settings>contact form CC field is an error that has been recently fixed in the settings package: it's because the migration seed is missing the actual field information (how it should look and work - in the ```field``` column). You can just delete the ```contact_email``` and contact_cc``` rows from your db, they were just examples anyway;
- PageManager only helps you edit the information in the database, in order to correctly preview the pages you need to code the front-end for that; [here's an example](https://github.com/Laravel-Backpack/PageManager/issues/2#issuecomment-225615723);
- NewsCRUD (Articles) has no front-end provided right now; you have to code your own, using you own application's design;

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.
