### ISSUE TITLE
Missing config files

### ISSUE THREAD

**Issue by johnpuddephatt** [Laravel-Backpack/Demo#78]
# Bug report

### What I did:
Installed package following instructions

### What I expected to happen:
To see base.php and crud.php in config/backpack

### What happened:
They were missing

### Backpack, Laravel, PHP, DB version:
Backpack V4 / Laravel V6

**Comment by tabacitu** [comment]
Huh, that's weird. I just tested twice - and both times they got published for me. Did you follow the [installation guide](https://backpackforlaravel.com/docs/4.0/installation) or the [upgrade guide](https://backpackforlaravel.com/docs/4.0/upgrade-guide)?

**Comment by tabacitu** [comment]
(I mean - was it on an existing Laravel project or on a fresh Laravel install)

**Comment by johnpuddephatt** [comment]
This is from a fresh install of Laravel-Backpack/Demo.

Firstly... should `@php artisan vendor:publish --provider='Backpack\\CRUD\\BackpackServiceProvider'`
be added in `post-install-cmd` as well as `post-update-cmd` in composer.json? 

Secondly... should `--tag=public` be removed? The config file publish command is tagged 'config'.

**Comment by tabacitu** [comment]
@johnpuddephatt - you were right, as usual :-)

Indeed, the ```crud``` and ```base``` config files were missing - looks like I removed them when upgrading to v4. They're now in the folder by default, as expected.

I've removed the publish command from both ```post-install-cmd``` and ```post-update-cmd```, since:
- it's not actually needed upon installation, the assets are already published in ```public```;
- I've removed that ```post-update-cmd``` step from the Backpack installation process, because it overwrote A LOT of files, that were commited to version control; so every time you did a ```composer update```, it basically added a few dozen MB to your git repo; not cool; this of course prevents us from pushing CSS&JS updates without breaking changes [just like in v3 :-( ]; which sucks; but at least we're not bloating people's git repos;
